name: "trivy-go-plugin"
repository: github.com/afdesk/trivy-go-plugin
version: "0.0.1"
usage: trivy go plugin
description: |-
  A Trivy plugin
platforms:
  -
    uri: https://github.com/afdesk/trivy-go-plugin/releases/download/v0.0.1/trivy-go-plugin_0.0.1_Linux-amd64.tar.gz
    bin: ./trivy-go-plugin
