name: Release

on:
    push:
        branches:
            - main
        paths:
            - 'plugin.yaml'
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        uses: afdesk/trivy-go-plugin/.github/workflows/simple-release.yaml@main
