name: Simple release

on:
    workflow_call:

jobs:
    check-version:
        uses: afdesk/trivy-go-plugin/.github/workflows/check-version.yaml@main

    release:
        needs: check-version
        uses: afdesk/trivy-go-plugin/.github/workflows/release-go.yaml@main
        with:
            next-version: ${{ needs.check-version.outputs.next-version }}
